CREATE TABLE `T_CUSTOMER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUST_ADDRESS` varchar(250) NOT NULL,
  `CUST_EMAIL` varchar(100) NOT NULL,
  `CUST_NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_T_CUSTOMER` (`CUST_EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `T_ORDER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ORD_GROS_PRICE` double NOT NULL,
  `ORD_NUMBER` varchar(100) NOT NULL,
  `ORD_QTY` double NOT NULL,
  `CUST_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_ORD_NUMBER` (`ORD_NUMBER`),
  KEY `FK_T_ORDER_CUST_ID` (`CUST_ID`),
  CONSTRAINT `FK_T_ORDER_CUST_ID` FOREIGN KEY (`CUST_ID`) REFERENCES `T_CUSTOMER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

